image: openjdk:13-jdk-buster
clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly
pipelines:
  default:
    - step:
        caches:
          - gradle
          - gradlewrapper
        script:
          - ./gradlew build

definitions:
  caches:
    sonar: ~/.sonar/cache
    gradlewrapper: ~/.gradle/wrapper
