image: openjdk:13-jdk-buster
clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly
pipelines:
  default:
    - step:
        caches:
          - gradle
          - gradlewrapper
        script:
          - ./gradlew build
          - export FILE="$(ls build/libs/*.jar | sort -V | tail -n1)"
          - pipe: atlassian/bitbucket-upload-file:0.1.2
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_USERNAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
              FILENAME: "$FILE"
definitions:
  caches:
    sonar: ~/.sonar/cache
    gradlewrapper: ~/.gradle/wrapper
