on:
    workflow_dispatch: null
    push:
        branches:
        - main
name: Branch main
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
        -   name: Check out repository code
            uses: actions/checkout@v2
        -   name: Cache
            uses: actions/cache@v2
            with:
                path: |-
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ runner.os }}-cache-gradle_caches_gradle_wrapper
        -   name: Run gradlew publish
            run: ./gradlew publish
            env:
                GITHUB_TOKEN: ${{ github.token  }}
