on:
    workflow_dispatch: null
    push:
        branches:
        - '**'
name: Default
jobs:
    gradle-test:
        runs-on: ubuntu-latest
        steps:
        -   name: Check out repository code
            uses: actions/checkout@v2
        - uses: actions/setup-java@v3
          with:
              distribution: 'temurin'
              java-version: '17'
        -   name: Cache
            uses: actions/cache@v2
            with:
                path: |-
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ runner.os }}-cache-gradle_caches_gradle_wrapper
        -   name: Run gradlew test
            run: ./gradlew test

